
services:
  es:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: es
    environment:
      - node.name=es-node
      - cluster.name=search-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "${ES_HTTPS_PORT}:${ES_HTTPS_PORT}" # https
      - "${ES_TCP_PORT}:${ES_TCP_PORT}" #tcp

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: "${ELASTICSEARCH_HOST}"
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    depends_on:
      - es

  redis:
    image: redis:7.2
    container_name: noti
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  mongo:
    image: mongo:8.0.8
    container_name: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db


  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: spring-app
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SPRING_ELASTICSEARCH_URIS: ${ELASTICSEARCH_URIS}
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PAYMENT_SECRET_KEY: ${PAYMENT_SECRET_KEY}
      PAYMENT_CLIENT_KEY: ${PAYMENT_CLIENT_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_CLOUDFRONT_DOMAIN: ${AWS_CLOUDFRONT_DOMAIN}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - mongo
      - redis
      - es

volumes:
  es-data:
    driver: local
  redis-data:
    driver: local
  mongo-data:
    driver: local
