spring:
  application:
    name: palayo
  datasource:
    url: jdbc:mysql://localhost:3306/palayo_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  config:
    import:
      - classpath:/local/application-local.yml
    firebase:
      config-path: classpath:palayo-auction-test-firebase-adminsdk-fbsvc-d7b4c29e3d.json