name: Java CI with Gradle

on:
  push:
    branches:
      - feat/**
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle Wrapper에 실행 권한 부여
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      # 4. Gradle로 JAR 빌드
      - name: Build with Gradle
        run: ./gradlew clean bootJar

      # 5. JAR 파일을 아티팩트로 업로드
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/palayo-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build  # build 작업 성공 시 실행

    steps:
      # 1. 아티팩트 다운로드
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      # 2. EC2에 JAR 파일 복사
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}   # ex) ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "palayo-0.0.1-SNAPSHOT.jar"
          target: "/home/${{ secrets.EC2_USER }}/app"

      # 3. EC2에서 Spring Boot 애플리케이션 재시작
      - name: Restart Spring Boot App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
                 - name: Restart Spring Boot App
                 uses: appleboy/ssh-action@v1.0.3
                 with:
                   host: ${{ secrets.EC2_HOST }}
                   username: ${{ secrets.EC2_USER }}
                   key: ${{ secrets.EC2_SSH_KEY }}
                   script: |
                     pkill -f 'java -jar' || true
                     cd /home/ubuntu/app
                     screen -S spring_boot_session -d -m java -jar palayo-0.0.1-SNAPSHOT.jar
                     sleep 3
          
          
      
